hybrid/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url('^$', RedirectView.as_view(url='/hybridapp/')),
    url(r'^admin/', admin.site.urls),
    url(r'^hybridapp/', include('hybridapp.urls')),
]

hybridapp/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'hybridapp'

urlpatterns = [
    url(r'^$', views.home, name='main'),
    url(r'^home/$', views.home, name='home'),
    url(r'^new/$', views.new, name='new'),
    url(r'^success/$', views.success, name='success'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^projects/$', views.projects, name='projects'),
    url(r'^projectbids/(?P<project_id>\d+)', views.projectbids, name='projectbids'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^oauth/redirect/$', views.oauth_redirect, name='oauth_redirect'),
    url(r'^oauth/$', views.oauth, name='oauth')
]

hybridapp/models.py
from django.db import models
import requests
import json

import proselint
from enchant.checker import SpellChecker
import language_check
import execjs
import os
import sys
import math

# Create your models here.
class Bid(object):
    def __init__(self, text):
        self.text = text

    @staticmethod
    def get_quality_score(text):
        n_characters = len(text)
        n_errors = Bid.get_total_errors(text)[0]
        return math.atan(n_characters / ((n_errors ** 1.7) * 1.0)) / math.pi * 200
        
    @staticmethod
    def get_total_errors(text):
        n_errors = 0
        a = LanguageCheck.get_error_count(text)
        b = ProseLint.get_error_count(text)
        c = PyEnchant.get_error_count(text)
        d = Pedant.get_error_count(text)
        n_errors = a+b+c+d
        return n_errors, a, b, c, d
    
# Checks grammar and spelling
class LanguageCheck():
    @staticmethod
    def get_error_count(text):
        tool = language_check.LanguageTool('en-AU')
        matches = tool.check(text)
        return len(matches)
    
    @staticmethod
    def fix(text):
        tool = language_check.LanguageTool('en-AU')
        matches = tool.check(text)
        return language_check.correct(text, matches)
    
# Checks grammar
class ProseLint():
    @staticmethod
    def get_suggestions(text):
        suggestions = proselint.tools.lint(text)
        return suggestions

    @staticmethod
    def get_error_count(text):
        suggestions = proselint.tools.lint(text)
        return(len(suggestions))

        
# Checks spelling
# You need to install some dependecies for PyEnchant to work
# https://stackoverflow.com/questions/21083059/enchant-c-library-not-found-while-installing-pyenchant-using-pip-on-osx
# Reference for PyEnchant: http://pythonhosted.org/pyenchant/tutorial.html
class PyEnchant():
    @staticmethod
    def get_errors(text):
        checker = SpellChecker("en_AU")
        checker.set_text(text)
        return checker

    @staticmethod
    def get_error_count(text):
        checker = SpellChecker("en_AU")
        checker.set_text(text)
        return len(list(checker))
        
# Checks punctuation
# https://github.com/Decagon/Pedant 
# You need to:
# make init-js
# Uses this as reference: https://www.codementor.io/jstacoder/integrating-nodejs-python-how-to-write-cross-language-modules-pyexecjs-du107xfep
class Pedant():
    @staticmethod
    def get_error_count(lines):
        runtime = execjs.get('Node')
        context = runtime.compile('''
            module.paths.push('%s');
            var pedant = require('pedantjs');
            function validate(lines) {
                return pedant.validate(lines);
            }
        ''' % os.path.join(os.path.dirname(__file__),'node_modules'))

        result = context.call("validate", lines)
        return result

class Project(object):
    def __init__(self, title, description, budget, jobs):
        self._title = title
        self._description = description
        self._budget = budget
        self._jobs = jobs

    # Title
    @property
    def title(self):
        return self._title

    @title.setter
    def title(self, value):
        if not value:
            raise ValueError("Title cannot be empty")
        self._title = value

    # Description
    @property
    def description(self):
        return self._description

    @description.setter
    def description(self, value):
        if not value:
            raise ValueError("Description cannot be empty")
        if len(value) < 5:
            data = json.dumps(data)
        self._description = value

    # Budget
    @property
    def budget(self):
        return self._budget

    @budget.setter
    def budget(self, value):
        self._budget = value


    # Jobs
    @property
    def jobs(self):
        return self._jobs

    @jobs.setter
    def jobs(self, value):
        self._jobs = value



class Budget(object):
    def __init__(self, minimum, maximum):
        self._max = maximum
        self._min = minimum

    # Maximum
    @property
    def maximum(self):
        return self._max

    @maximum.setter
    def maximum(self, value):
        if value < self.minimum:
            raise ValueError("maximum cannot be less than minimum")
        self._max = value

    # Minimum
    @property
    def minimum(self):
        return self._min

    @minimum.setter
    def minimum(self, value):
        if value > self.minimum:
            raise ValueError("minimum cannot be greater than maximum")
        self._min = value


class DBProject(models.Model):
    object_id = models.IntegerField(primary_key=True)

class DBProjectStore(object):
    def add_project(self, project):
        project.save()

    def get_project_ids(self):
        return [x.object_id for x in DBProject.objects.all()]

class ProjectStore(object):

    def post_project(self, project):
        headers = {
            'content-type': 'application/json',
            'freelancer-oauth-v1': employer_access_token,
        }

        params = (
            ('compact', ''),
        )

        data = {
            "title": project.title,
            "description": project.description,
            "currency": {
                "code": "AUD",
                "id": 3,
                "sign": "$"
            },
            "budget": {
                "minimum": project.budget.minimum,
                "maximum": project.budget.maximum
            },
            "jobs": [{"id": job_id} for job_id in project.jobs]
        }

        data = json.dumps(data)

        r = requests.post('https://www.freelancer-sandbox.com/api/projects/0.1/projects/',
                  headers=headers, params=params, data=data)

        project_id = r.json()["result"]["id"]

        # Print response
        print(r.json())

        return project_id



if __name__ == "__main__":
    budget = Budget(100, 200)
    project = Project("Matt Test", "Description test", budget, [3,17])
    store = ProjectStore()
    project_id = store.post_project(project)

    db_project = DBProject(project_id)
    db_project_store = DBProjectStore()
    db_project_store.add_project(db_project)
        

hybridapp/views.py
import requests

from django.urls import reverse
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect

from hybridapp.models import Budget, Project, ProjectStore, DBProject, DBProjectStore

# Import API calls
from hybridapp.services import *

# Import models
from hybridapp.models import *

# Homepage
def home(request):
    return render(request, 'hybridapp/home.html')

# Dashboard
def dashboard(request):
    return HttpResponseRedirect(reverse('hybridapp:projects'))

# Projects
def projects(request):
    user_id = 25832201
    projects = get_fl_projects_by_user_id(user_id)
    context = {
        'projects': projects
    }
    return render(request, 'hybridapp/projects.html', context=context)

# View to view bids for a specific project
def projectbids(request, project_id):
    bids = get_bids_by_project_id(project_id)
    
    # Order the bids
    bids = sorted(bids, key=lambda k: -int(k["quality_score"]))
    
    context = {
        'bids': bids
    }
    
    return render(request, 'hybridapp/projectbids.html', context=context)

# Logout
def logout(request):
    return HttpResponseRedirect(reverse('hybridapp:home'))

# View to create a new project
def new(request):

    if request.method == 'POST':
        # Get form fields
        project_name = request.POST.get('project-name')
        project_skills = request.POST.get('project-skills')
        project_learn = request.POST.get('project-learn')
        questions = request.POST.get('questions')
        min_bid = request.POST.get('min-bid')
        max_bid = request.POST.get('max-bid')

        print(project_skills)

        # Process POST data...
        # 1. Create project object
        budget = Budget(min_bid, max_bid)
        project = Project(project_name, project_learn, budget, [3,17])

        # 2. Call Freelancer API to post project, and retrieve project_id.
        store = ProjectStore()
        project_id = store.post_project(project)

        # 3. Store project_id in our local db.
        db_project = DBProject(project_id)
        db_project_store = DBProjectStore()
        db_project_store.add_project(db_project)

        # Redirect to success page
        return HttpResponseRedirect(reverse('hybridapp:success'))

        # N.B No error handling!!
        #15339120
        #15339110
        #15339118
    get_fl_project(15339120)

    return render(request, 'hybridapp/new.html')

# Page displayed upon successfully creating project.
def success(request):
    return render(request, 'hybridapp/success.html')

hybridapp/templates/hybridapp/dashboard.html
{% extends 'hybridapp/layout.html' %}
{% block navbar %}
{% include "hybridapp/includes/_navbar.html" %}
{% endblock %}
{% block content %}
<h2>Dashboard</h2>
<p>Welcome to your dashboard.</p>
{% endblock %}

hybridapp/templates/hybridapp/home.html
{% extends 'hybridapp/layout.html' %}

{% block content %}
<div class="ui center aligned container">
  <h1>Welcome to Freelancer Elite <i class="blue student icon"></i></h1>
  <a href="{% url 'hybridapp:oauth' %}"><button class="ui primary right labeled huge icon button">
        <i class="sign in icon"></i>
        Login with Freelancer
      </button></a>
    </div>
{% endblock %}

hybridapp/templates/hybridapp/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static "hybridapp/semantic/semantic.min.css" %}">
    <link rel="stylesheet" href="{% static "hybridapp/semantic/overrides.css" %}">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f" crossorigin="anonymous"></script>
    <script src="{% static "hybridapp/semantic/semantic.min.js" %}"></script>
    <title>Hybrid</title>
</head>

{% block css %}{% endblock %}

<body>
    <div class="ui centered grid">
        {% block navbar %}{% endblock %}
        <div class="ten wide computer twelve wide tablet sixteen wide mobile column">
            <div class="ui text container">
            {% block content %}{% endblock %}
        </div>
        </div>
    </div>
    {% block javascript %}{% endblock %}
</body>

</html>

hybridapp/templates/hybridapp/projectbids.html
{% extends 'hybridapp/layout.html' %}
{% block navbar %}
{% include "hybridapp/includes/_navbar.html" %}
{% endblock %}
{% load humanize %}
{% block content %}
<h2>Bids</h2>
<div class="ui cards">
    {% for bid in bids %}
    <div class="ui raised fluid card">
        <div class="content">
            <div class="header">A bid</div>
            <div class="meta">
                <span class="right floated time">{{ bid.submitdate|naturaltime }}</span>
                <span class="amount">${{ bid.amount }}</span>
            </div>
            <div class="description-fixed">
                <p>{{ bid.fixed }}</p>
            </div>
            <div class="ui segment description-orginal">
                <h3>Original Bid</h3>
                <p>{{ bid.description }}</p>
            </div>
        </div>
        <div class="extra content">
            <a class="errors" data-tooltip="{{ bid.errors }}" data-variation="wide">
                <i class="warning sign icon"></i>
                {{ bid.num_errors }} Error{{ bid.num_errors|pluralize }} in original bid
            </a>
            <span class="right floated num-errors">
                <i class="line chart icon"></i>
                Quality: {{ bid.quality_score|floatformat }}%
            </span>
        </div>
        <a class="ui green bottom attached labeled icon button" href="#"><i class="checkmark icon"></i> Accept bid</a>
    </div>
    {% empty %}
    <p>There are no bids for this project.</p>
    {% endfor %}
</div>
{% endblock %}

hybridapp/templates/hybridapp/projects.html
{% extends 'hybridapp/layout.html' %}
{% block navbar %}
{% include "hybridapp/includes/_navbar.html" %}
{% endblock %}
{% load humanize %}
{% block content %}
<h2>Projects</h2>
<div class="ui cards">
    {% for project in projects %}
    <div class="ui raised card">
        <div class="content">
            <span class="right floated"><i class="{{ project.currency.country|lower }} flag"></i></span>
            <div class="header">{{ project.title }}</div>
            <div class="meta">
                <span class="right floated time">{{ project.submitdate|naturaltime }}</span>
                <span class="budget">${{ project.budget.minimum }} - ${{ project.budget.maximum }}</span>
            </div>
            <div class="description">
                <p>{{ project.preview_description }}</p>
            </div>
        </div>
        <a href="{% url 'hybridapp:projectbids' project.id %}"class="ui teal bottom attached labeled
                 {% if project.frontend_project_status != 'open' %}disabled{% endif %} icon button">
            <i class="lab icon"></i>
            Analyse  {{ project.bid_stats.bid_count }} Bids
        </a>
    </div>
    {% empty %}
    <p>You have no existing projects.</p>
    {% endfor %}
</div>
{% endblock %}

hybridapp/templates/hybridapp/success.html
{% extends 'hybridapp/layout.html' %}
{% block navbar %}
{% include "hybridapp/includes/_navbar.html" %}
{% endblock %}
{% block content %}
    <h2>Project created!</h1>
    <p>You will be notified when we have located suitable tutors for your project.</h1>
    <br>
    <br>
    <a href="{% url 'hybridapp:dashboard' %}"><button class="ui button" type="submit">Return to dashboard</button></a>
{% endblock %}